# Ablation Study

In [1]:
from pathlib import Path
import json

import pandas as pd

In [2]:
experiment = "ablation_study"

In [3]:
# dataset = "aitv2"
# scenario = "santos"

In [4]:
dataset = "darpa2000"
scenario = "s1_inside"

## Metrics

In [5]:
results = {}
for baseline in ["multiclass", "ensemble"]:
    metrics_dir = Path(f"../../experiments/{dataset}/{scenario}/{experiment}/{baseline}/metrics")
    file_paths = list(metrics_dir.iterdir())
        
    for file_path in file_paths:
        experiment_name = file_path.stem
        print(experiment_name)

        # Load metrics
        with open(file_path, "r") as f:
            metrics = json.load(f)

        results[experiment_name] = {
            "macro_f1": metrics["macro_f1"],
            "accuracy": metrics["accuracy"],
            # "micro_f1": metrics["micro_f1"],
            "false_alarm_rate": metrics["false_alarm_rate"],
            "detection_rate": metrics["detection_rate"],
        }

multiclass_flowonlyfeatures_w10_fulldata_0.0001lr
multiclass_basefeatures_w100_fulldata_0.0001lr
multiclass_flowonlyfeatures_w10_fulldata_0.001lr
multiclass_basefeatures_w10_fulldata_0.0001lr
multiclass_flowonlyfeatures_w100_fulldata_0.001lr
multiclass_basefeatures_w100_fulldata_0.001lr
multiclass_basefeatures_w10_fulldata_0.001lr
multiclass_flowonlyfeatures_w100_fulldata_0.0001lr
ensemble_basefeatures_w100_fulldata_0.001lr
ensemble_basefeatures_w100_fulldata_0.0001lr
ensemble_flowonlyfeatures_w10_fulldata_0.0001lr
ensemble_basefeatures_w10_fulldata_0.001lr
ensemble_flowonlyfeatures_w100_fulldata_0.001lr
ensemble_flowonlyfeatures_w10_fulldata_0.001lr
ensemble_basefeatures_w10_fulldata_0.0001lr

In [6]:
results_df = pd.DataFrame(results).T
results_df

,macro_f1,accuracy,false_alarm_rate,detection_rate
multiclass_flowonlyfeatures_w10_fulldata_0.0001lr,0.822469,0.999319,0.000766,0.999515
multiclass_basefeatures_w100_fulldata_0.0001lr,0.842784,0.999330,0.000794,0.999553
multiclass_flowonlyfeatures_w10_fulldata_0.001lr,0.884956,0.999489,0.000465,0.999553
multiclass_basefeatures_w10_fulldata_0.0001lr,0.783588,0.999114,0.001230,0.999534
multiclass_flowonlyfeatures_w100_fulldata_0.001lr,0.879252,0.999511,0.000329,0.999534
multiclass_basefeatures_w100_fulldata_0.001lr,0.874379,0.999500,0.000411,0.999495
multiclass_basefeatures_w10_fulldata_0.001lr,0.914153,0.999569,0.000273,0.999534
multiclass_flowonlyfeatures_w100_fulldata_0.0001lr,0.847895,0.999239,0.001096,0.999573
ensemble_basefeatures_w100_fulldata_0.001lr,0.884299,0.999545,0.000329,0.999534
ensemble_basefeatures_w100_fulldata_0.0001lr,0.863598,0.999477,0.000438,0.999534
ensemble_flowonlyfeatures_w10_fulldata_0.0001lr,0.878318,0.999444,0.000547,0.999534
ensemble_basefeatures_w10_fulldata_0.001lr,0.915163,0.999580,0.000301,0.999573
ensemble_flowonlyfeatures_w100_fulldata_0.001lr,0.881677,0.999534,0.000301,0.999515
ensemble_flowonlyfeatures_w10_fulldata_0.001lr,0.913115,0.999546,0.000410,0.999592
ensemble_basefeatures_w10_fulldata_0.0001lr,0.862689,0.999444,0.000520,0.999573

In [7]:
results_df_sorted_f1 = results_df.sort_values("macro_f1", ascending=False)
results_df_sorted_f1

,macro_f1,accuracy,false_alarm_rate,detection_rate
ensemble_basefeatures_w10_fulldata_0.001lr,0.915163,0.999580,0.000301,0.999573
multiclass_basefeatures_w10_fulldata_0.001lr,0.914153,0.999569,0.000273,0.999534
ensemble_flowonlyfeatures_w10_fulldata_0.001lr,0.913115,0.999546,0.000410,0.999592
multiclass_flowonlyfeatures_w10_fulldata_0.001lr,0.884956,0.999489,0.000465,0.999553
ensemble_basefeatures_w100_fulldata_0.001lr,0.884299,0.999545,0.000329,0.999534
ensemble_flowonlyfeatures_w100_fulldata_0.001lr,0.881677,0.999534,0.000301,0.999515
multiclass_flowonlyfeatures_w100_fulldata_0.001lr,0.879252,0.999511,0.000329,0.999534
ensemble_flowonlyfeatures_w10_fulldata_0.0001lr,0.878318,0.999444,0.000547,0.999534
multiclass_basefeatures_w100_fulldata_0.001lr,0.874379,0.999500,0.000411,0.999495
ensemble_basefeatures_w100_fulldata_0.0001lr,0.863598,0.999477,0.000438,0.999534
ensemble_basefeatures_w10_fulldata_0.0001lr,0.862689,0.999444,0.000520,0.999573
multiclass_flowonlyfeatures_w100_fulldata_0.0001lr,0.847895,0.999239,0.001096,0.999573
multiclass_basefeatures_w100_fulldata_0.0001lr,0.842784,0.999330,0.000794,0.999553
multiclass_flowonlyfeatures_w10_fulldata_0.0001lr,0.822469,0.999319,0.000766,0.999515
multiclass_basefeatures_w10_fulldata_0.0001lr,0.783588,0.999114,0.001230,0.999534

In [8]:
# Save results
reports_dir = Path(f"../../reports/{dataset}/{scenario}/{experiment}")
reports_dir.mkdir(parents=True, exist_ok=True)

results_df_sorted_f1.to_csv(
    reports_dir / "metrics.csv",
    index=True
)