# Ablation Study

In [18]:
from pathlib import Path
import json

import pandas as pd

In [25]:
experiment = "ablation_study"

In [19]:
dataset = "aitv2"
scenario = "santos"

## Metrics

In [21]:
results = {}
for baseline in ["multiclass", "ensemble"]:
    metrics_dir = Path(f"../../experiments/{dataset}/{scenario}/{experiment}/{baseline}/metrics")
    file_paths = list(metrics_dir.iterdir())
        
    for file_path in file_paths:
        experiment_name = file_path.stem
        print(experiment_name)

        # Load metrics
        with open(file_path, "r") as f:
            metrics = json.load(f)

        results[experiment_name] = {
            "macro_f1": metrics["macro_f1"],
            "accuracy": metrics["accuracy"],
            # "micro_f1": metrics["micro_f1"],
            "false_alarm_rate": metrics["false_alarm_rate"],
            "detection_rate": metrics["detection_rate"],
        }

multiclass_flowonlyfeatures_w10_fulldata_0.0001lr
multiclass_basefeatures_w100_fulldata_0.0001lr
multiclass_flowonlyfeatures_w10_fulldata_0.001lr
multiclass_basefeatures_w10_fulldata_0.0001lr
multiclass_flowonlyfeatures_w100_fulldata_0.001lr
multiclass_basefeatures_w100_fulldata_0.001lr
multiclass_basefeatures_w10_fulldata_0.001lr
multiclass_flowonlyfeatures_w100_fulldata_0.0001lr
ensemble_flowonlyfeatures_w100_fulldata_0.0001lr
ensemble_basefeatures_w100_fulldata_0.001lr
ensemble_basefeatures_w100_fulldata_0.0001lr
ensemble_flowonlyfeatures_w10_fulldata_0.0001lr
ensemble_basefeatures_w10_fulldata_0.001lr
ensemble_flowonlyfeatures_w100_fulldata_0.001lr
ensemble_flowonlyfeatures_w10_fulldata_0.001lr
ensemble_basefeatures_w10_fulldata_0.0001lr

In [22]:
results_df = pd.DataFrame(results).T
results_df

,macro_f1,accuracy,false_alarm_rate,detection_rate
multiclass_flowonlyfeatures_w10_fulldata_0.0001lr,0.415273,0.862278,0.143356,0.966081
multiclass_basefeatures_w100_fulldata_0.0001lr,0.691932,0.987389,0.012447,0.984554
multiclass_flowonlyfeatures_w10_fulldata_0.001lr,0.420804,0.865862,0.139570,0.966082
multiclass_basefeatures_w10_fulldata_0.0001lr,0.622739,0.985854,0.013642,0.977793
multiclass_flowonlyfeatures_w100_fulldata_0.001lr,0.636735,0.930704,0.071528,0.970556
multiclass_basefeatures_w100_fulldata_0.001lr,0.821338,0.995191,0.004309,0.986456
multiclass_basefeatures_w10_fulldata_0.001lr,0.674925,0.992333,0.006695,0.975588
multiclass_flowonlyfeatures_w100_fulldata_0.0001lr,0.483079,0.888934,0.116216,0.980674
ensemble_flowonlyfeatures_w100_fulldata_0.0001lr,0.519067,0.908274,0.095211,0.970324
ensemble_basefeatures_w100_fulldata_0.001lr,0.864978,0.996605,0.002871,0.987446
ensemble_basefeatures_w100_fulldata_0.0001lr,0.749813,0.990731,0.009033,0.986685
ensemble_flowonlyfeatures_w10_fulldata_0.0001lr,0.420362,0.868470,0.136811,0.965321
ensemble_basefeatures_w10_fulldata_0.001lr,0.674073,0.992406,0.006648,0.975968
ensemble_flowonlyfeatures_w100_fulldata_0.001lr,0.597265,0.920872,0.082183,0.975576
ensemble_flowonlyfeatures_w10_fulldata_0.001lr,0.430028,0.877963,0.126348,0.957867
ensemble_basefeatures_w10_fulldata_0.0001lr,0.636477,0.988012,0.011191,0.974219

In [23]:
results_df_sorted_f1 = results_df.sort_values("macro_f1", ascending=False)
results_df_sorted_f1

,macro_f1,accuracy,false_alarm_rate,detection_rate
ensemble_basefeatures_w100_fulldata_0.001lr,0.864978,0.996605,0.002871,0.987446
multiclass_basefeatures_w100_fulldata_0.001lr,0.821338,0.995191,0.004309,0.986456
ensemble_basefeatures_w100_fulldata_0.0001lr,0.749813,0.990731,0.009033,0.986685
multiclass_basefeatures_w100_fulldata_0.0001lr,0.691932,0.987389,0.012447,0.984554
multiclass_basefeatures_w10_fulldata_0.001lr,0.674925,0.992333,0.006695,0.975588
ensemble_basefeatures_w10_fulldata_0.001lr,0.674073,0.992406,0.006648,0.975968
multiclass_flowonlyfeatures_w100_fulldata_0.001lr,0.636735,0.930704,0.071528,0.970556
ensemble_basefeatures_w10_fulldata_0.0001lr,0.636477,0.988012,0.011191,0.974219
multiclass_basefeatures_w10_fulldata_0.0001lr,0.622739,0.985854,0.013642,0.977793
ensemble_flowonlyfeatures_w100_fulldata_0.001lr,0.597265,0.920872,0.082183,0.975576
ensemble_flowonlyfeatures_w100_fulldata_0.0001lr,0.519067,0.908274,0.095211,0.970324
multiclass_flowonlyfeatures_w100_fulldata_0.0001lr,0.483079,0.888934,0.116216,0.980674
ensemble_flowonlyfeatures_w10_fulldata_0.001lr,0.430028,0.877963,0.126348,0.957867
multiclass_flowonlyfeatures_w10_fulldata_0.001lr,0.420804,0.865862,0.139570,0.966082
ensemble_flowonlyfeatures_w10_fulldata_0.0001lr,0.420362,0.868470,0.136811,0.965321
multiclass_flowonlyfeatures_w10_fulldata_0.0001lr,0.415273,0.862278,0.143356,0.966081

In [29]:
# Save results
reports_dir = Path(f"../../reports/{dataset}/{scenario}/{experiment}")
reports_dir.mkdir(parents=True, exist_ok=True)

results_df_sorted_f1.to_csv(
    reports_dir / "metrics.csv",
    index=True
)