# Analyze DARPA 2000 Attack Phases

In [1]:
import pandas as pd

## Load Attack Data

In [2]:
dataset = "darpa2000"
scenario = "s1_inside"
data_dir = f"../data/interim/{dataset}/{scenario}/flows_unlabeled"

In [3]:
dfs = []

attack_phases = list(range(1, 6)) 
for phase in attack_phases:
    print(f"Phase: {phase}")

    df = pd.read_csv(
        f"{data_dir}/phase{phase}_flows.csv"
    )

    dfs.append(df)

Phase: 1
Phase: 2
Phase: 3
Phase: 4
Phase: 5

In [4]:
def analyze_phase(df, print_details=True):

    src_ips = df["src_ip"].value_counts()
    dst_ips = df["dst_ip"].value_counts()
    src_ports = df["sport"].value_counts()
    dst_ports = df["dport"].value_counts()

    if print_details:
        print("Total Flows:", len(df))

        print("\n --- IP distribution ---")
        print(f"\nSource IPs ({len(src_ips)}):")
        print(src_ips)
        print(f"\nDestination IPs ({len(dst_ips)}):")
        print(dst_ips)

        print("\n --- Port distribution ---")
        print(f"Source Ports ({len(src_ports)}):")
        print(src_ports)
        print(f"\nDestination Ports ({len(dst_ports)}):")
        print(dst_ports)

    return src_ips, dst_ips, src_ports, dst_ports

## Phase 1: IP Sweep

In [5]:
df_1 = dfs[0]
df_1

,flow_id,start_time,end_time,duration,src_ip,sport,dst_ip,dport,proto,service,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,f0,9.524407e+08,9.524407e+08,0.000153,202.77.162.213,8,172.16.112.100,0,icmp,-,...,F,T,0,-,1,38,1,38,-,1
1,f1,9.524407e+08,9.524407e+08,0.000168,202.77.162.213,8,172.16.112.50,0,icmp,-,...,F,T,0,-,1,38,1,38,-,1
2,f2,9.524407e+08,9.524407e+08,0.000000,202.77.162.213,8,172.16.112.20,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
3,f3,9.524407e+08,9.524407e+08,0.000000,202.77.162.213,8,172.16.112.149,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
4,f4,9.524407e+08,9.524407e+08,0.000000,202.77.162.213,8,172.16.115.5,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
5,f5,9.524407e+08,9.524407e+08,0.003379,202.77.162.213,8,172.16.112.105,0,icmp,-,...,F,T,0,-,1,38,1,38,-,1
6,f6,9.524407e+08,9.524407e+08,24.675615,172.16.112.194,0,202.77.162.213,8,icmp,-,...,T,F,0,-,11,418,1,38,-,1
7,f7,9.524407e+08,9.524407e+08,0.000197,202.77.162.213,8,172.16.115.20,0,icmp,-,...,F,T,0,-,1,38,1,38,-,1
8,f8,9.524407e+08,9.524407e+08,0.000000,202.77.162.213,8,172.16.113.207,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
9,f9,9.524407e+08,9.524407e+08,0.000774,202.77.162.213,8,172.16.115.87,0,icmp,-,...,F,T,0,-,1,38,1,38,-,1
10,f10,9.524407e+08,9.524407e+08,0.000000,202.77.162.213,8,172.16.115.234,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
11,f11,9.524407e+08,9.524407e+08,0.000193,202.77.162.213,8,172.16.113.50,0,icmp,-,...,F,T,0,-,1,38,1,38,-,1
12,f12,9.524407e+08,9.524407e+08,0.000000,202.77.162.213,8,172.16.113.84,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
13,f13,9.524407e+08,9.524407e+08,0.000000,202.77.162.213,8,172.16.112.207,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
14,f14,9.524407e+08,9.524407e+08,0.000050,202.77.162.213,8,172.16.112.10,0,icmp,-,...,F,T,0,-,1,38,1,38,-,1
15,f15,9.524407e+08,9.524407e+08,0.000000,202.77.162.213,8,172.16.113.204,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
16,f16,9.524407e+08,9.524407e+08,0.000768,202.77.162.213,8,172.16.113.105,0,icmp,-,...,F,T,0,-,1,38,1,38,-,1
17,f17,9.524407e+08,9.524407e+08,0.000843,202.77.162.213,8,172.16.113.148,0,icmp,-,...,F,T,0,-,1,38,1,38,-,1
18,f18,9.524407e+08,9.524407e+08,0.000000,202.77.162.213,8,172.16.113.168,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1
19,f19,9.524407e+08,9.524407e+08,0.000000,202.77.162.213,8,172.16.113.169,0,icmp,-,...,F,T,0,-,1,38,0,0,-,1

In [6]:
src_ips_1, dst_ips_1, src_ports_1, dst_ports_1 = analyze_phase(df_1)

Total Flows: 20

 --- IP distribution ---

Source IPs (2):
src_ip
202.77.162.213    19
172.16.112.194     1
Name: count, dtype: int64

Destination IPs (20):
dst_ip
172.16.112.100    1
172.16.112.50     1
172.16.112.20     1
172.16.112.149    1
172.16.115.5      1
172.16.112.105    1
202.77.162.213    1
172.16.115.20     1
172.16.113.207    1
172.16.115.87     1
172.16.115.234    1
172.16.113.50     1
172.16.113.84     1
172.16.112.207    1
172.16.112.10     1
172.16.113.204    1
172.16.113.105    1
172.16.113.148    1
172.16.113.168    1
172.16.113.169    1
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (2):
sport
8    19
0     1
Name: count, dtype: int64

Destination Ports (2):
dport
0    19
8     1
Name: count, dtype: int64

## Phase 2: Sadmind Ping

In [7]:
df_2 = dfs[1]
df_2

,flow_id,start_time,end_time,duration,src_ip,sport,dst_ip,dport,proto,service,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,f0,9.524417e+08,9.524417e+08,0.001404,202.77.162.213,54790,172.16.115.20,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
1,f1,9.524417e+08,9.524417e+08,0.121346,202.77.162.213,54792,172.16.115.20,32773,udp,-,...,F,T,0,Dd,1,100,1,52,-,17
2,f2,9.524417e+08,9.524417e+08,55.105987,202.77.162.213,54793,172.16.115.87,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
3,f3,9.524417e+08,9.524417e+08,55.105984,172.16.112.194,3,202.77.162.213,3,icmp,-,...,T,F,0,-,10,1120,0,0,-,1
4,f4,9.524417e+08,9.524417e+08,20.040411,172.16.115.87,3,202.77.162.213,3,icmp,-,...,T,F,0,-,2,224,0,0,-,1
5,f5,9.524419e+08,9.524419e+08,0.002883,202.77.162.213,55484,172.16.113.50,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
6,f6,9.524419e+08,9.524419e+08,0.000000,172.16.113.105,3,202.77.162.213,3,icmp,-,...,T,F,0,-,1,112,0,0,-,1
7,f7,9.524419e+08,9.524419e+08,0.000000,172.16.117.132,3,202.77.162.213,3,icmp,-,...,T,F,0,-,1,112,0,0,-,1
8,f8,9.524419e+08,9.524420e+08,55.095633,202.77.162.213,55485,172.16.113.105,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
9,f9,9.524420e+08,9.524420e+08,55.097466,202.77.162.213,55884,172.16.113.148,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
10,f10,9.524420e+08,9.524420e+08,55.097567,172.16.113.148,3,202.77.162.213,3,icmp,-,...,T,F,0,-,4,448,0,0,-,1
11,f11,9.524419e+08,9.524420e+08,110.206492,172.16.112.194,3,202.77.162.213,3,icmp,-,...,T,F,0,-,18,2016,0,0,-,1
12,f12,9.524421e+08,9.524421e+08,0.000959,202.77.162.213,56254,172.16.112.10,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
13,f13,9.524421e+08,9.524421e+08,0.057435,202.77.162.213,56256,172.16.112.10,32774,udp,-,...,F,T,0,Dd,1,100,1,52,-,17
14,f14,9.524421e+08,9.524421e+08,0.001479,202.77.162.213,56260,172.16.112.50,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
15,f15,9.524421e+08,9.524421e+08,0.085001,202.77.162.213,56262,172.16.112.50,32773,udp,-,...,F,T,0,Dd,1,100,1,52,-,17
16,f16,9.524421e+08,9.524422e+08,55.104855,202.77.162.213,56263,172.16.112.100,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
17,f17,9.524421e+08,9.524422e+08,55.104831,172.16.112.100,3,202.77.162.213,3,icmp,-,...,T,F,0,-,12,672,0,0,-,1
18,f18,9.524422e+08,9.524422e+08,55.095159,202.77.162.213,56413,172.16.112.105,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17
19,f19,9.524422e+08,9.524422e+08,55.093929,172.16.112.105,3,202.77.162.213,3,icmp,-,...,T,F,0,-,12,672,0,0,-,1
20,f20,9.524422e+08,9.524423e+08,55.097203,172.16.112.194,3,202.77.162.213,3,icmp,-,...,T,F,0,-,12,1344,0,0,-,1
21,f21,9.524422e+08,9.524423e+08,55.097220,202.77.162.213,56577,172.16.112.194,111,udp,-,...,F,T,0,D,12,1008,0,0,-,17

In [8]:
src_ips_2, dst_ips_2, src_ports_2, dst_ports_2 = analyze_phase(df_2)

Total Flows: 22

 --- IP distribution ---

Source IPs (8):
src_ip
202.77.162.213    13
172.16.112.194     3
172.16.115.87      1
172.16.113.105     1
172.16.117.132     1
172.16.113.148     1
172.16.112.100     1
172.16.112.105     1
Name: count, dtype: int64

Destination IPs (11):
dst_ip
202.77.162.213    9
172.16.115.20     2
172.16.112.10     2
172.16.112.50     2
172.16.115.87     1
172.16.113.105    1
172.16.113.50     1
172.16.113.148    1
172.16.112.100    1
172.16.112.105    1
172.16.112.194    1
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (14):
sport
3        9
54790    1
54792    1
54793    1
55484    1
55485    1
55884    1
56254    1
56256    1
56260    1
56262    1
56263    1
56413    1
56577    1
Name: count, dtype: int64

Destination Ports (4):
dport
111      10
3         9
32773     2
32774     1
Name: count, dtype: int64

In [9]:
different_dst_ips = dst_ips_1.index.difference(dst_ips_2.index)
different_dst_ips

Index(['172.16.112.149', '172.16.112.20', '172.16.112.207', '172.16.113.168',
       '172.16.113.169', '172.16.113.204', '172.16.113.207', '172.16.113.84',
       '172.16.115.234', '172.16.115.5'],
      dtype='object', name='dst_ip')

In [10]:
# Check which homenet IPs are involved in each phase
common_dst_ips = dst_ips_1.index.intersection(dst_ips_2.index)
common_dst_ips

Index(['172.16.112.100', '172.16.112.50', '172.16.112.105', '202.77.162.213',
       '172.16.115.20', '172.16.115.87', '172.16.113.50', '172.16.112.10',
       '172.16.113.105', '172.16.113.148'],
      dtype='object', name='dst_ip')

In [11]:
active_ips = dst_ips_1.index.intersection(src_ips_2.index)
active_ips

Index(['172.16.112.100', '172.16.112.105', '202.77.162.213', '172.16.115.87',
       '172.16.113.105', '172.16.113.148'],
      dtype='object')

## Phase 3: Exploiting

In [12]:
df_3 = dfs[2]
df_3

,flow_id,start_time,end_time,duration,src_ip,sport,dst_ip,dport,proto,service,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,f0,9.524432e+08,9.524432e+08,8.321712,202.77.162.213,46956,172.16.115.20,23,tcp,-,...,F,T,0,ShAdDaFf,14,778,13,799,-,6
1,f1,9.524432e+08,9.524432e+08,8.318017,202.77.162.213,46958,172.16.115.20,23,tcp,-,...,F,T,0,ShAdDaFf,13,726,13,799,-,6
2,f2,9.524432e+08,9.524432e+08,1.605300,202.77.162.213,46959,172.16.115.20,23,tcp,-,...,F,T,0,ShAdDaFf,13,726,13,839,-,6
3,f3,9.524432e+08,9.524432e+08,0.001303,202.77.162.213,60249,172.16.115.20,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
4,f4,9.524432e+08,9.524432e+08,0.000000,202.77.162.213,60251,172.16.115.20,32773,udp,-,...,F,T,0,D,1,1440,0,0,-,17
5,f5,9.524432e+08,9.524432e+08,0.001259,202.77.162.213,60253,172.16.115.20,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
6,f6,9.524432e+08,9.524432e+08,0.000000,202.77.162.213,60255,172.16.115.20,32773,udp,-,...,F,T,0,D,1,1440,0,0,-,17
7,f7,9.524432e+08,9.524432e+08,0.001255,202.77.162.213,60267,172.16.115.20,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
8,f8,9.524432e+08,9.524432e+08,0.000000,202.77.162.213,60269,172.16.115.20,32773,udp,-,...,F,T,0,D,1,1440,0,0,-,17
9,f9,9.524432e+08,9.524432e+08,0.001274,202.77.162.213,60274,172.16.115.20,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
10,f10,9.524432e+08,9.524432e+08,0.000000,202.77.162.213,60276,172.16.115.20,32773,udp,-,...,F,T,0,D,1,1440,0,0,-,17
11,f11,9.524432e+08,9.524432e+08,0.001249,202.77.162.213,60287,172.16.115.20,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
12,f12,9.524432e+08,9.524432e+08,0.000000,202.77.162.213,60289,172.16.115.20,32773,udp,-,...,F,T,0,D,1,1440,0,0,-,17
13,f13,9.524432e+08,9.524432e+08,0.001289,202.77.162.213,60298,172.16.115.20,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
14,f14,9.524432e+08,9.524432e+08,0.000000,202.77.162.213,60300,172.16.115.20,32773,udp,-,...,F,T,0,D,1,1440,0,0,-,17
15,f15,9.524433e+08,9.524433e+08,8.276784,202.77.162.213,46986,172.16.112.10,23,tcp,-,...,F,T,0,ShAdDFaf,14,622,12,626,-,6
16,f16,9.524433e+08,9.524433e+08,4.323372,202.77.162.213,46987,172.16.112.10,23,tcp,-,...,F,T,0,ShAdDFaf,14,622,13,762,-,6
17,f17,9.524433e+08,9.524433e+08,0.400089,202.77.162.213,47014,172.16.112.50,23,tcp,-,...,F,T,0,ShAdD,13,582,12,1793,-,6
18,f18,9.524433e+08,9.524433e+08,0.001355,202.77.162.213,60617,172.16.112.50,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
19,f19,9.524433e+08,9.524433e+08,0.000000,202.77.162.213,60605,172.16.112.50,32773,udp,-,...,F,T,0,D,1,1440,0,0,-,17
20,f20,9.524433e+08,9.524433e+08,0.000000,202.77.162.213,60619,172.16.112.50,32773,udp,-,...,F,T,0,D,1,1440,0,0,-,17
21,f21,9.524433e+08,9.524433e+08,0.001628,202.77.162.213,60603,172.16.112.50,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
22,f22,9.524433e+08,9.524433e+08,8.326679,202.77.162.213,46988,172.16.112.50,23,tcp,-,...,F,T,0,ShAdDFaf,14,622,12,627,-,6
23,f23,9.524433e+08,9.524433e+08,0.001369,202.77.162.213,60576,172.16.112.50,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
24,f24,9.524433e+08,9.524433e+08,0.000000,202.77.162.213,60569,172.16.112.50,32773,udp,-,...,F,T,0,D,1,1440,0,0,-,17
25,f25,9.524433e+08,9.524433e+08,0.001537,202.77.162.213,60567,172.16.112.50,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
26,f26,9.524433e+08,9.524433e+08,0.000859,202.77.162.213,60547,172.16.112.10,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
27,f27,9.524433e+08,9.524433e+08,0.000000,202.77.162.213,60549,172.16.112.10,32774,udp,-,...,F,T,0,D,1,1440,0,0,-,17
28,f28,9.524433e+08,9.524433e+08,0.000000,202.77.162.213,60542,172.16.112.10,32774,udp,-,...,F,T,0,D,1,1440,0,0,-,17
29,f29,9.524433e+08,9.524433e+08,0.000924,202.77.162.213,60540,172.16.112.10,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
30,f30,9.524433e+08,9.524433e+08,0.000000,202.77.162.213,60578,172.16.112.50,32773,udp,-,...,F,T,0,D,1,1440,0,0,-,17
31,f31,9.524433e+08,9.524433e+08,0.000000,202.77.162.213,60524,172.16.112.10,32774,udp,-,...,F,T,0,D,1,1440,0,0,-,17
32,f32,9.524433e+08,9.524433e+08,0.000841,202.77.162.213,60522,172.16.112.10,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17
33,f33,9.524433e+08,9.524433e+08,0.000000,202.77.162.213,60519,172.16.112.10,32774,udp,-,...,F,T,0,D,1,1440,0,0,-,17
34,f34,9.524433e+08,9.524433e+08,0.001261,202.77.162.213,60517,172.16.112.10,111,udp,-,...,F,T,0,Dd,1,84,1,56,-,17

In [13]:
src_ips_3, dst_ips_3, src_ports_3, dst_ports_3 = analyze_phase(df_3)

Total Flows: 35

 --- IP distribution ---

Source IPs (1):
src_ip
202.77.162.213    35
Name: count, dtype: int64

Destination IPs (3):
dst_ip
172.16.115.20    15
172.16.112.10    10
172.16.112.50    10
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (35):
sport
46956    1
46958    1
46959    1
60249    1
60251    1
60253    1
60255    1
60267    1
60269    1
60274    1
60276    1
60287    1
60289    1
60298    1
60300    1
46986    1
46987    1
47014    1
60617    1
60605    1
60619    1
60603    1
46988    1
60576    1
60569    1
60567    1
60547    1
60549    1
60542    1
60540    1
60578    1
60524    1
60522    1
60519    1
60517    1
Name: count, dtype: int64

Destination Ports (4):
dport
111      14
32773    10
23        7
32774     4
Name: count, dtype: int64

## Phase 4: Installation

In [14]:
df_4 = dfs[3]
df_4

,flow_id,start_time,end_time,duration,src_ip,sport,dst_ip,dport,proto,service,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,f0,9.524442e+08,9.524442e+08,1.235002,172.16.115.20,1022,202.77.162.213,514,tcp,-,...,T,F,0,ShADadfF,26,1119,38,45725,-,6
1,f1,9.524442e+08,9.524442e+08,0.012167,202.77.162.213,47014,172.16.112.50,23,tcp,-,...,F,T,0,FafA,2,80,2,80,-,6
2,f2,9.524442e+08,9.524442e+08,0.184623,172.16.115.20,1023,202.77.162.213,514,tcp,-,...,T,F,0,ShADadFf,7,370,6,296,-,6
3,f3,9.524442e+08,9.524442e+08,1.112859,172.16.115.20,1022,202.77.162.213,514,tcp,-,...,T,F,0,ShADadFf,7,370,7,336,-,6
4,f4,9.524442e+08,9.524442e+08,1.253746,172.16.115.20,1021,202.77.162.213,514,tcp,-,...,T,F,0,ShADadfF,31,1319,48,61297,-,6
5,f5,9.524442e+08,9.524442e+08,1.238906,202.77.162.213,1023,172.16.115.20,514,tcp,-,...,F,T,0,ShADadFR,7,403,6,354,-,6
6,f6,9.524442e+08,9.524442e+08,4.253701,202.77.162.213,47496,172.16.115.20,23,tcp,-,...,F,T,0,ShAdDafF,30,1888,29,2018,-,6
7,f7,9.524442e+08,9.524442e+08,0.208764,202.77.162.213,1023,172.16.115.20,514,tcp,-,...,F,T,0,ShADadFR,6,365,5,327,-,6
8,f8,9.524442e+08,9.524442e+08,0.176527,172.16.112.10,1023,202.77.162.213,514,tcp,-,...,T,F,0,ShADadFf,8,410,6,296,-,6
9,f9,9.524442e+08,9.524442e+08,1.276797,172.16.112.10,1022,202.77.162.213,514,tcp,-,...,T,F,0,ShADaTdfF,18,870,38,45725,-,6
10,f10,9.524442e+08,9.524442e+08,1.818671,202.77.162.213,47502,172.16.112.10,23,tcp,-,...,F,T,0,ShAdDfFa,24,1197,23,1347,-,6
11,f11,9.524442e+08,9.524442e+08,0.177512,172.16.112.50,1023,202.77.162.213,514,tcp,-,...,T,F,0,ShADadfF,6,330,5,256,-,6
12,f12,9.524442e+08,9.524442e+08,0.150412,202.77.162.213,1023,172.16.112.10,514,tcp,-,...,F,T,0,ShADadFR,6,317,5,263,-,6
13,f13,9.524442e+08,9.524442e+08,0.327980,172.16.112.50,1023,202.77.162.213,514,tcp,-,...,T,F,0,ShADadfF,17,759,37,45685,-,6
14,f14,9.524442e+08,9.524442e+08,1.001106,202.77.162.213,47512,172.16.112.50,23,tcp,-,...,F,T,0,ShAdDfFa,24,1197,24,2499,-,6
15,f15,9.524443e+08,9.524443e+08,0.000383,172.16.112.50,1023,202.77.162.213,1022,tcp,-,...,T,F,0,ShA,2,84,1,44,-,6
16,f16,9.524443e+08,9.524443e+08,0.187361,202.77.162.213,1023,172.16.112.50,514,tcp,-,...,F,T,0,ShADadFR,6,317,5,263,-,6
17,f17,9.524442e+08,9.524442e+08,0.000404,172.16.112.10,1022,202.77.162.213,1022,tcp,-,...,T,F,0,ShA,2,84,1,44,-,6
18,f18,9.524442e+08,9.524442e+08,0.000339,172.16.115.20,1020,202.77.162.213,1022,tcp,-,...,T,F,0,ShA,2,84,1,44,-,6
19,f19,9.524442e+08,9.524442e+08,0.000351,172.16.115.20,1021,202.77.162.213,1022,tcp,-,...,T,F,0,ShA,2,84,1,44,-,6

In [15]:
src_ips_4, dst_ips_4, src_ports_4, dst_ports_4 = analyze_phase(df_4)

Total Flows: 20

 --- IP distribution ---

Source IPs (4):
src_ip
202.77.162.213    8
172.16.115.20     6
172.16.112.10     3
172.16.112.50     3
Name: count, dtype: int64

Destination IPs (4):
dst_ip
202.77.162.213    12
172.16.112.50      3
172.16.115.20      3
172.16.112.10      2
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (8):
sport
1023     9
1022     4
1021     2
47014    1
47496    1
47502    1
47512    1
1020     1
Name: count, dtype: int64

Destination Ports (3):
dport
514     12
23       4
1022     4
Name: count, dtype: int64

## Phase 5: Launching DDoS

In [16]:
df_5 = dfs[4]
df_5

,flow_id,start_time,end_time,duration,src_ip,sport,dst_ip,dport,proto,service,...,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,ip_proto
0,f0,9.524464e+08,9.524464e+08,0.000658,172.16.115.20,1020,202.77.162.213,1022,tcp,-,...,T,F,0,FafA,2,80,2,80,-,6
1,f1,9.524465e+08,9.524465e+08,0.000000,8.138.161.2,4845,131.84.1.31,12277,tcp,-,...,F,F,0,A,1,40,0,0,-,6
2,f2,9.524465e+08,9.524465e+08,0.000000,8.138.161.2,4939,131.84.1.31,4047,tcp,-,...,F,F,0,A,1,40,0,0,-,6
3,f3,9.524465e+08,9.524465e+08,0.000000,8.138.161.2,17060,131.84.1.31,3462,tcp,-,...,F,F,0,A,1,40,0,0,-,6
4,f4,9.524465e+08,9.524465e+08,0.000000,61.56.80.155,4940,131.84.1.31,31938,tcp,-,...,F,F,0,A,1,40,0,0,-,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73467,f73467,9.524473e+08,9.524473e+08,0.095554,172.16.115.5,26717,131.84.1.31,80,tcp,http,...,T,F,0,ShADadfF,11,756,18,21837,-,6
73468,f73468,9.524473e+08,9.524473e+08,0.053366,172.16.115.5,26716,131.84.1.31,80,tcp,http,...,T,F,0,ShADadfF,7,581,9,6530,-,6
73469,f73469,9.524473e+08,9.524473e+08,0.031198,172.16.115.5,26715,131.84.1.31,80,tcp,http,...,T,F,0,ShADdfFa,5,511,4,2432,-,6
73470,f73470,9.524473e+08,9.524473e+08,0.042587,172.16.115.5,26714,131.84.1.31,80,tcp,http,...,T,F,0,ShADdfFa,6,501,6,4445,-,6
73471,f73471,9.524464e+08,9.524469e+08,485.687292,202.77.162.213,49212,172.16.115.20,23,tcp,-,...,F,T,0,ShADad,306,16235,175,10646,-,6

In [17]:
src_ips_5, dst_ips_5, src_ports_5, dst_ports_5 = analyze_phase(df_5)

Total Flows: 73472

 --- IP distribution ---

Source IPs (34167):
src_ip
131.84.1.31        27
172.16.115.5       22
172.16.116.201      9
86.127.75.214       3
66.205.254.252      3
                   ..
4.85.210.8          1
105.234.76.148      1
124.218.225.96      1
90.155.73.37        1
101.156.196.187     1
Name: count, Length: 34167, dtype: int64

Destination IPs (30):
dst_ip
131.84.1.31        73443
202.77.162.213         1
65.1.244.117           1
15.195.61.30           1
20.212.147.130         1
15.20.26.74            1
46.100.78.94           1
14.197.191.227         1
61.149.25.187          1
103.39.94.48           1
55.212.151.19          1
107.74.199.78          1
7.34.96.82             1
109.132.158.112        1
12.199.8.97            1
88.85.116.233          1
29.67.164.138          1
40.231.78.143          1
95.52.180.11           1
104.176.136.157        1
24.26.5.176            1
0.123.102.208          1
22.132.227.28          1
101.22.197.206         1
3.233.137.243          1
45.177.162.9           1
118.105.150.101        1
27.87.200.255          1
100.102.86.165         1
172.16.115.20          1
Name: count, dtype: int64

 --- Port distribution ---
Source Ports (34246):
sport
25009    4
24713    4
23083    4
23266    4
24714    4
        ..
39111    1
39110    1
39109    1
39108    1
39107    1
Name: count, Length: 34246, dtype: int64

Destination Ports (29272):
dport
80       34
30161    11
6682     10
1015     10
14218     9
         ..
11840     1
4632      1
29289     1
13972     1
23951     1
Name: count, Length: 29272, dtype: int64

In [21]:
counter = 0
for ip in df_5["dst_ip"]:
    if ip.startswith("172.16."):
        counter += 1
print(f"Number of destination IPs in phase 5 that are in the homenet: {counter}")

Number of destination IPs in phase 5 that are in the homenet: 1